"""
build_ui.py — gzip + embed UI files into firmware as PROGMEM arrays.

Reads everything in data/ folder, gzip-compresses each file, generates
include/ui_pages.h with binary arrays. Hook ke platformio.ini via
extra_scripts = pre:scripts/build_ui.py supaya otomatis re-generated
sebelum tiap compile.

Pattern dipinjam dari WLED (https://github.com/wled/WLED) yang embed
seluruh UI di firmware sebagai gzipped binary. Browser otomatis
decompress karena response header punya Content-Encoding: gzip.

Benefits vs LittleFS approach:
  * OTA firmware update = update UI sekaligus
  * Gzip compression rasio 3-5x = serve lebih cepat
  * No LittleFS corruption risk
  * Browser caches gzip-encoded response

Trade-off: firmware.bin ~150 KB lebih besar, edit UI butuh rebuild
firmware (slower iteration during dev — workaround: tetap pakai
uploadfs LittleFS untuk dev cycle cepat, embed cuma untuk production
build).
"""

import os
import gzip
import re
from pathlib import Path

try:
    Import("env")  # PlatformIO injection
    PLATFORMIO = True
except NameError:
    PLATFORMIO = False
    env = None

# ─── Konfigurasi ──────────────────────────────────────────────────
# PlatformIO SCons context tidak punya __file__. Fallback ke
# env["PROJECT_DIR"] kalau jalan dari PIO, else infer dari script path.
if PLATFORMIO:
    PROJECT_DIR = Path(env["PROJECT_DIR"])
else:
    PROJECT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR    = PROJECT_DIR / "data"
OUT_HEADER  = PROJECT_DIR / "include" / "ui_pages.h"

# Mapping ekstensi file -> C identifier safe + MIME type
MIME_BY_EXT = {
    ".html": "text/html",
    ".htm":  "text/html",
    ".css":  "text/css",
    ".js":   "application/javascript",
    ".json": "application/json",
    ".svg":  "image/svg+xml",
    ".png":  "image/png",
    ".ico":  "image/x-icon",
    ".txt":  "text/plain",
}


def safe_ident(filename: str) -> str:
    """Convert filename to a safe C identifier.
    "index.html" -> "PAGE_index_html"
    "app.js"     -> "PAGE_app_js"
    """
    name = re.sub(r"[^A-Za-z0-9]", "_", filename)
    return "PAGE_" + name


def gzip_compress(data: bytes) -> bytes:
    """Max compression, no mtime header (deterministic output)."""
    import io
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


def format_bytes_as_c(data: bytes, indent: str = "    ") -> str:
    """Format bytes as C-array hex literals, 16 per line."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join("0x%02x" % b for b in chunk)
        lines.append(indent + hex_vals)
    return ",\n".join(lines)


def generate_header(files: list) -> str:
    """Generate complete header file content."""
    lines = []
    lines.append("// AUTO-GENERATED by scripts/build_ui.py — DO NOT EDIT")
    lines.append("// Source files in data/ folder.")
    lines.append("// Each PAGE_xxx[] adalah gzipped binary representation of the file.")
    lines.append("// http_server.cpp serves these dengan Content-Encoding: gzip header.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("#include <pgmspace.h>")
    lines.append("")
    lines.append("namespace cdi::ui::pages {")
    lines.append("")

    # Per-file arrays
    for f in files:
        ident = f["ident"]
        size = len(f["gz"])
        raw_size = f["raw_size"]
        ratio = f["ratio"]
        lines.append("// %s (%d -> %d bytes, gzip %.1f%%)" %
                     (f["filename"], raw_size, size, ratio))
        lines.append("const uint16_t %s_len  = %d;" % (ident, size))
        lines.append("const char     %s_path[] = \"%s\";" % (ident, f["http_path"]))
        lines.append("const char     %s_mime[] = \"%s\";" % (ident, f["mime"]))
        lines.append("const uint8_t  %s[] PROGMEM = {" % ident)
        lines.append(format_bytes_as_c(f["gz"]))
        lines.append("};")
        lines.append("")

    # Index struct untuk lookup
    lines.append("// ─── Index table — iterate untuk match request path ───")
    lines.append("struct PageEntry {")
    lines.append("    const char*    path;")
    lines.append("    const char*    mime;")
    lines.append("    const uint8_t* data;")
    lines.append("    uint16_t       len;")
    lines.append("};")
    lines.append("")
    lines.append("constexpr size_t kPageCount = %d;" % len(files))
    lines.append("const PageEntry kPages[kPageCount] = {")
    for f in files:
        ident = f["ident"]
        lines.append("    { %s_path, %s_mime, %s, %s_len }," %
                     (ident, ident, ident, ident))
    lines.append("};")
    lines.append("")
    lines.append("} // namespace cdi::ui::pages")
    lines.append("")

    return "\n".join(lines)


def build(*_args, **_kwargs):
    if not DATA_DIR.exists():
        print("[build_ui] DATA_DIR not found: %s" % DATA_DIR)
        return

    files = []
    total_raw = 0
    total_gz  = 0

    for entry in sorted(DATA_DIR.iterdir()):
        if not entry.is_file():
            continue
        ext = entry.suffix.lower()
        mime = MIME_BY_EXT.get(ext)
        if not mime:
            print("[build_ui] skip (unknown ext): %s" % entry.name)
            continue

        raw = entry.read_bytes()
        gz = gzip_compress(raw)
        ratio = (len(gz) / len(raw) * 100.0) if raw else 0.0

        # HTTP path = "/" + filename, except index -> "/" too
        if entry.name in ("index.html", "index.htm"):
            http_path = "/"
        else:
            http_path = "/" + entry.name

        files.append({
            "filename":  entry.name,
            "http_path": http_path,
            "mime":      mime,
            "raw_size":  len(raw),
            "gz":        gz,
            "ratio":     ratio,
            "ident":     safe_ident(entry.name),
        })
        total_raw += len(raw)
        total_gz  += len(gz)
        print("[build_ui]   %-18s %6d -> %5d B (%.1f%%)  %s" %
              (entry.name, len(raw), len(gz), ratio, mime))

    # Generate header
    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text(generate_header(files), encoding="utf-8")

    overall_ratio = (total_gz / total_raw * 100.0) if total_raw else 0.0
    print("[build_ui] total %d files · raw %d B -> gz %d B (%.1f%%) -> %s" %
          (len(files), total_raw, total_gz, overall_ratio,
           OUT_HEADER.relative_to(PROJECT_DIR)))


# Direct invocation (manual test)
if __name__ == "__main__":
    build()

# PlatformIO pre-action hook
if PLATFORMIO:
    print("[build_ui] PlatformIO pre-build action registered")
    env.AddPreAction("buildprog", build)
    # Also run immediately so the header exists for the first compile
    build()
